<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
//    protected  $tabble='posts';
    protected $fillable = ['title','alias','description','content'];
    public function getRouteKeyName()
    {
        return 'alias'; // TODO: Change the autogenerated stub
    }
    public function user(){
        return $this->belongsTo('App\User');
    }
    public function getPostComment(){
        return $this->hasMany('App\Comment');
    }

}
